# Generated by Django 4.1.13 on 2023-12-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
        ("product", "0002_productanalysis_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalysis",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_auth.user",
            ),
        ),
    ]
