# Generated by Django 4.1.13 on 2023-12-28 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_productanalysis_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalysis",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
