# Generated by Django 4.1.13 on 2023-12-28 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_rename_content_productanalysis_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("detail", models.CharField(max_length=50, null=True)),
                ("weight", models.CharField(max_length=50, null=True)),
                ("create_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PriceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("price", models.CharField(max_length=50, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
