# Generated by Django 4.1.13 on 2023-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_product_pricechange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
