# Generated by Django 4.1.13 on 2023-12-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_alter_product_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricechange",
            name="max_price",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pricechange",
            name="min_price",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
