# Generated by Django 4.1.13 on 2023-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_pricechange_max_price_pricechange_min_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="productanalysis",
            name="is_reading",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
