# Generated by Django 4.1.13 on 2024-01-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_productanalysis_is_reading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productanalysis",
            name="is_reading",
            field=models.BooleanField(default=False),
        ),
    ]
