# Generated by Django 4.1.13 on 2023-12-26 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("weight", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.CharField(max_length=500)),
                (
                    "status",
                    models.IntegerField(choices=[(1, "접수"), (2, "처리중"), (3, "완료")]),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
                    ),
                ),
            ],
            options={
                "db_table": "report",
            },
        ),
    ]
