# Generated by Django 4.1.13 on 2023-12-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0002_alter_report_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="content",
            field=models.CharField(default="", max_length=500),
        ),
    ]
