# Generated by Django 4.1.13 on 2023-12-29 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0004_reportimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportimage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
