# Generated by Django 4.1.13 on 2024-01-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
        ("report", "0005_alter_reportimage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.IntegerField(
                choices=[(1, "보류"), (2, "의심"), (3, "슈링크")], default=1
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_likes",
                        to="report.report",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_likes",
                        to="user_auth.user",
                    ),
                ),
            ],
            options={
                "db_table": "report_like",
                "unique_together": {("report", "user")},
            },
        ),
    ]
