# Generated by Django 4.1.13 on 2024-01-03 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0007_report_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShrinkFlationGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report.report"
                    ),
                ),
            ],
        ),
    ]
