# Generated by Django 4.1.13 on 2024-01-05 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_product_image"),
        ("report", "0009_shrinkflationgeneration_after_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shrinkflationgeneration",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="shrinkflationgeneration",
            name="report",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.report",
            ),
        ),
    ]
