# Generated by Django 4.1.13 on 2024-01-08 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_product_image"),
        ("report", "0011_alter_shrinkflationgeneration_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shrinkflationgeneration",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                unique=True,
            ),
        ),
    ]
