# Generated by Django 4.1.13 on 2024-01-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0014_remove_report_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="product_name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
