# Generated by Django 4.1.13 on 2023-12-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0001_initial"),
        ("query", "0002_commentlike_commentdislike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
            ),
        ),
        migrations.AlterField(
            model_name="commentdislike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
            ),
        ),
        migrations.AlterField(
            model_name="commentlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
            ),
        ),
        migrations.AlterField(
            model_name="dislike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
            ),
        ),
        migrations.AlterField(
            model_name="queryboard",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
            ),
        ),
        migrations.AlterField(
            model_name="view",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_auth.user"
            ),
        ),
    ]
