# Generated by Django 4.1.13 on 2023-12-27 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("query", "0003_alter_comment_user_alter_commentdislike_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="user",
            new_name="writer",
        ),
    ]
